### ISSUE TITLE
Everything works but it can't save

### ISSUE THREAD

**Issue by LivelyCarpet87** [ProGamerGov/Protobuf-Dreamer#2]
I get the error: 'Image' object has no attribute 'dtype'
Note: i updated to python 3. 
Full error:
Traceback (most recent call last):
  File "pb_dreamer.py", line 152, in <module>
    imsave("output_name", output_img)
  File "/usr/local/lib/python3.7/site-packages/skimage/io/_io.py", line 142, in imsave
    if arr.dtype == bool:
AttributeError: 'Image' object has no attribute 'dtype'

**Comment by LivelyCarpet87** [comment]
Solution: Use "matplotlib.pyplot.imsave(output_name, output_img):
Import matplotlib
from matplotlib import pyplot
